### PR TITLE
Add package_data entry in setup.py

### PR DESCRIPTION
**Pull request by dfroger**
See: https://docs.python.org/2/distutils/setupscript.html#installing-package-data

### CODE REVIEW

**Comment by dfroger** [comment]
This shoud fix #2

**Comment by dfroger** [comment]
Does files in `less` directory generate files in `static` directory?

I this case, shoud we distribute  files in `less` directory?

**Comment by pmorissette** [comment]
Hey @dfroger , 

Thanks for your pull request!

I don't think we should include the less directory by default. Less is only if someone wants to modify the theme. In this case, it would be best to clone the source files and make modifications from there. 

Could you please remove the less files? I will then merge to fix #2.

Thanks for your input,

Phil

**Comment by dfroger** [comment]
Hi @pmorissette,

I removed the less files from the install.

This is ready to merge, but if your prefer, I can rebase on the last master commit.

Thanks,
David

**Comment by pmorissette** [comment]
Hey @dfroger,

Please do and I will merge!

Thanks again,
Phil

**Comment by dfroger** [comment]
done!

**Comment by pmorissette** [comment]
Great thanks!

**Pull request merged**
